#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'curb'

KEY = 'YOUR_API_KEY_HERE'
curl = Curl::Easy.new

Dir['**/*.nfo'].each do |file|
  imdb = File.open(file, :encoding => "BINARY").grep(/imdb.com/i).first
  imdb.sub!(/.*imdb.com.*?(\d+).*/i, '\1')

  doc = Nokogiri::HTML(open("http://api.themoviedb.org/2.1/Movie.getImages/en/xml/#{KEY}/tt#{imdb}"))

  puts "Fetching: #{doc.xpath('//movie/name').inner_text}\n"
  doc.xpath('//images/backdrop').each do |backdrop|
    backdrop.xpath('./image[@width="1920"]').each do |image|
      next if File.exists?("#{File.dirname(file)}/backdrop-#{image.parent['id']}.jpg")
      curl.url = image.parent.xpath('./image[@size="thumb"]').first['url']
      curl.perform
      File.open("#{File.dirname(file)}/backdrop-#{image.parent['id']}.jpg", 'w') {|f| f.write(curl.body_str)}
    end
  end

  doc.xpath('//images/poster/image[@size="thumb"]').each do |poster|
    next if File.exists?("#{File.dirname(file)}/poster-#{poster.parent['id']}.jpg")
    curl.url = poster['url']
    curl.perform
    File.open("#{File.dirname(file)}/poster-#{poster.parent['id']}.jpg", 'w') {|f| f.write(curl.body_str)}
  end
end
